config/routes.rb
Rails.application.routes.draw do
  concern :thumbs do
    resources :thumbs
  end

  root to: 'high_voltage/pages#show', id: 'home'

  devise_for :users
  resources :beds, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :linens, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :purchases, only: [:edit, :update, :show]

  namespace :back_end do
    resources :beds, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :colors, concerns: [:thumbs]
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'bed_prices', only: [:show, :edit, :update]
      resource  :kit_prices, controller: 'kit_prices', only: [:show, :edit, :update]
    end
    resources :purchases, only: [:index]

    resources :linens, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'linen_prices', only: [:show, :edit, :update]
    end
    resources :linen_purchases, only: [:index]
  end
end

app/models/bed_price.rb
class BedPrice < ActiveRecord::Base
  belongs_to :bed
  belongs_to :dimension
end

# == Schema Information
#
# Table name: bed_prices
#
#  id             :integer          not null, primary key
#  bed_id         :integer
#  has_decoration :boolean          default(FALSE)
#  has_rack       :boolean          default(FALSE)
#  dimension_id   :integer
#  price          :decimal(10, 2)   default(0.0)
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/back_end/bed_prices_controller.rb
class BackEnd::BedPricesController < BackEndController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  # GET /beds/1
  def show
  end

  # GET /beds/1/edit
  def edit
  end

  # PATCH/PUT /beds/1
  def update
    if @bed.update(bed_params)
      redirect_to back_end_bed_prices_path(@bed), notice: "Veiksmīgi tika labotas gultas '#{@bed.name}' cenas"
    else
      render :edit
    end
  end

  private

  def set_bed
    @bed = Bed.find(params[:bed_id])
  end

  def bed_params
    params.require(:bed).permit(bed_prices_attributes: [
      :id, :kit_id, :dimension_id, :has_decoration, :has_rack, :price
    ])
  end
end

app/controllers/back_end/beds_controller.rb
class BackEnd::BedsController < BackEndController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  # GET /beds
  def index
    @beds = Bed.all.order(sequence: :asc)
  end

  # GET /beds/1
  def show
  end

  # GET /beds/new
  def new
    @bed = Bed.new
  end

  # GET /beds/1/edit
  def edit
  end

  # POST /beds
  def create
    @bed = Bed.new(bed_params)

    if @bed.save
      redirect_to back_end_bed_path(@bed), notice: "Veiksmīgi tika izveidota gulta '#{@bed.name}'"
    else
      render :new
    end
  end

  # PATCH/PUT /beds/1
  def update
    if @bed.update(bed_params)
      redirect_to back_end_bed_path(@bed), notice: "Veiksmīgi tika labota gulta '#{@bed.name}'"
    else
      render :edit
    end
  end

  # DELETE /beds/1
  def destroy
    @bed.destroy
    redirect_to back_end_beds_url, notice: 'Bed was successfully destroyed.'
  end

  private

  def set_bed
    @bed = Bed.find(params[:id])
  end

  def bed_params
    params.require(:bed).permit(
      :code, :name, :sequence, :has_decoration, :has_rack, :description_lv, :description_ru, :description_en
    )
  end
end

app/controllers/back_end/colors_controller.rb
class BackEnd::ColorsController < BackEndController
  before_action :set_itemable
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /{:bed_id}/colors
  def index
    @colors = @itemable.colors.order(sequence: :asc)
  end

  # GET /{:bed_id}/colors/1
  def show
  end

  # GET /{:bed_id}/colors/new
  def new
    @color = @itemable.colors.new
  end

  # GET /{:bed_id}/colors/1/edit
  def edit
  end

  # POST /{:bed_id}/colors
  def create
    @color = @itemable.colors.new(color_params)

    if @color.save
      redirect_to polymorphic_path([:back_end, @itemable, @color]), notice: 'Color was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /{:bed_id}/colors/1
  def update
    if @color.update(color_params)
      redirect_to polymorphic_path([:back_end, @itemable, @color]), notice: 'Color was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /{:bed_id}/colors/1
  def destroy
    @color.destroy
    redirect_to polymorphic_path([:back_end, @itemable, :colors]), notice: 'Color was successfully destroyed.'
  end

  private

  def set_color
    @color = @itemable.colors.find(params[:id])
  end

  def set_itemable
    @itemable = Bed.find(params[:bed_id])
  end

  def color_params
    params.require(:color).permit(:name_lv, :name_en, :name_ru)
  end
end

app/controllers/back_end/dimensions_controller.rb
class BackEnd::DimensionsController < BackEndController
  before_action :set_itemable
  before_action :set_dimension, only: [:show, :edit, :update, :destroy]

  # GET /{:bed_id}/dimensions
  def index
    @dimensions = @itemable.dimensions.order(sequence: :asc)
  end

  # GET /{:bed_id}/dimensions/1
  def show
  end

  # GET /{:bed_id}/dimensions/new
  def new
    @dimension = @itemable.dimensions.new
  end

  # GET /{:bed_id}/dimensions/1/edit
  def edit
  end

  # POST /{:bed_id}/dimensions
  def create
    @dimension = @itemable.dimensions.new(dimension_params)

    if @dimension.save
      redirect_to polymorphic_path([:back_end, @itemable, @dimension]), notice: 'Dimension was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /{:bed_id}/dimensions/1
  def update
    if @dimension.update(dimension_params)
      redirect_to polymorphic_path([:back_end, @itemable, @dimension]), notice: 'Dimension was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /{:bed_id}/dimensions/1.json
  def destroy
    @dimension.destroy
    redirect_to polymorphic_path([:back_end, @itemable, :dimensions]), notice: 'Dimension was successfully destroyed.'
  end

  private

  def set_dimension
    @dimension = @itemable.dimensions.find(params[:id])
  end

  def set_itemable
    if params[:bed_id]
      @itemable = Bed.find(params[:bed_id])
    else
      @itemable = Linen.find(params[:linen_id])
    end
  end

  def dimension_params
    params.require(:dimension).permit(:name, :short_name, :is_default, :sequence)
  end
end

app/controllers/back_end/kit_prices_controller.rb
class BackEnd::KitPricesController < BackEndController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  # GET /beds/1
  def show
  end

  # GET /beds/1/edit
  def edit
  end

  # PATCH/PUT /beds/1
  def update
    if @bed.update(bed_params)
      redirect_to back_end_bed_kit_prices_path(@bed), notice: "Veiksmīgi tika labotas gultas '#{@bed.name}' komplektu cenas"
    else
      render :edit
    end
  end

  private

  def set_bed
    @bed = Bed.find(params[:bed_id])
  end

  def bed_params
    params.require(:bed).permit(kit_prices_attributes: [
      :id, :dimension_id, :kit_id, :price
    ])
  end
end

app/controllers/back_end/kits_controller.rb
class BackEnd::KitsController < BackEndController
  before_action :set_itemable
  before_action :set_kit, only: [:show, :edit, :update, :destroy]

  # GET /{:bed_id}/kits
  def index
    @kits = @itemable.kits.order(sequence: :asc)
  end

  # GET /{:bed_id}/kits/1
  def show
  end

  # GET /{:bed_id}/kits/new
  def new
    @kit = @itemable.kits.new
  end

  # GET /{:bed_id}/kits/1/edit
  def edit
  end

  # POST /{:bed_id}/kits
  def create
    @kit = @itemable.kits.new(kit_params)

    if @kit.save
      redirect_to polymorphic_path([:back_end, @itemable, @kit]), notice: 'Kit was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /{:bed_id}/kits/1
  def update
    if @kit.update(kit_params)
      redirect_to polymorphic_path([:back_end, @itemable, @kit]), notice: 'Kit was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /{:bed_id}/kits/1
  def destroy
    @kit.destroy
    redirect_to polymorphic_path([:back_end, @itemable, :kits]), notice: 'Kit was successfully destroyed.'
  end

  private

  def set_kit
    @kit = @itemable.kits.find(params[:id])
  end

  def set_itemable
    if params[:bed_id]
      @itemable = Bed.find(params[:bed_id])
    else
      @itemable = Linen.find(params[:linen_id])
    end
  end

  def kit_params
    params.require(:kit).permit(:name_lv, :name_en, :name_ru, :sequence, :is_default, :description_lv, :description_en, :description_ru)
  end
end

app/controllers/back_end/linen_prices_controller.rb
class BackEnd::LinenPricesController < BackEndController
  before_action :set_linen, only: [:show, :edit, :update, :destroy]

  # GET /back_end/linens/1
  def show
  end

  # GET /back_end/linens/1/edit
  def edit
  end

  # PATCH/PUT /back_end/linens/1
  def update
    if @linen.update(linen_params)
      redirect_to back_end_linen_prices_path(@linen), notice: "Veiksmīgi tika labotas gultas '#{@linen.name}' komplektu cenas"
    else
      render :edit
    end
  end

  private

  def set_linen
    @linen = Linen.find(params[:linen_id])
  end

  def linen_params
    params.require(:linen).permit(linen_prices_attributes: [
      :id, :dimension_id, :has_decoration, :kit_id, :price
    ])
  end
end

app/controllers/back_end/linens_controller.rb
class BackEnd::LinensController < BackEndController
  before_action :set_linen, only: [:show, :edit, :update, :destroy]

  # GET /back_end/linens
  def index
    @linens = Linen.all.order(sequence: :asc)
  end

  # GET /back_end/linens/1
  def show
  end

  # GET /back_end/linens/new
  def new
    @linen = Linen.new
  end

  # GET /back_end/linens/1/edit
  def edit
  end

  # POST /back_end/linens
  def create
    @linen = Linen.new(linen_params)

    if @linen.save
      redirect_to back_end_linen_path(@linen), notice: "Veiksmīgi tika izveidots komplekts '#{@linen.name}'"
    else
      render :new
    end
  end

  # PATCH/PUT /back_end/linens/1
  def update
    if @linen.update(linen_params)
      redirect_to back_end_linen_path(@linen), notice: "Veiksmīgi tika labots komplekts '#{@linen.name}'"
    else
      render :edit
    end
  end

  # DELETE /back_end/linens/1
  def destroy
    @linen.destroy
    redirect_to back_end_linens_url, notice: 'LInen was successfully destroyed.'
  end

  private

  def set_linen
    @linen = Linen.find(params[:id])
  end

  def linen_params
    params.require(:linen).permit(
      :code, :name, :sequence, :has_decoration, :description_lv, :description_ru, :description_en
    )
  end
end

app/controllers/back_end/purchases_controller.rb
class BackEnd::PurchasesController < BackEndController
  def index
    @purchases = Purchase.all.order(created_at: :desc).limit(50)
  end
end

app/controllers/back_end/thumbs_controller.rb
class BackEnd::ThumbsController < BackEndController
  before_action :load_thumbable
  before_action :load_thumb, only: [:show, :destroy]

  # GET /thumbs
  def index
    @thumbs = @thumbable.thumbs.all
  end

  # GET /thumbs/1
  def show
    @thumb = @thumbable.thumbs.find(params[:id])
  end

  # GET /thumbs/new
  def new
    @thumb = @thumbable.thumbs.new
  end

  # GET /thumbs/1/edit
  def edit
    @thumb = @thumbable.thumbs.find(params[:id])
  end

  # POST /thumbs
  def create
    @thumb = @thumbable.thumbs.new(thumb_params)

    if @thumb.save
      redirect_to polymorphic_path([:back_end, @itemable, @thumbable, @thumb]), notice: 'Photo was successfully created'
    else
      render :new
    end
  end

  # PUT /thumbs/1
  def update
    @thumb = @thumbable.thumbs.find(params[:id])

    if @thumb.update_attributes(thumb_params)
      redirect_to polymorphic_path([:back_end, @itemable, @thumbable, @thumb]), notice: 'Photo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /thumbs/1
  def destroy
    @thumb = @thumbable.thumbs.find(params[:id])
    @thumb.destroy

    redirect_to polymorphic_path([:back_end, @itemable, @thumbable, :thumbs])
  end

  private

  def load_thumb
    @thumb = @thumbable.thumbs.find(params[:id])
  end

  def load_thumbable
    @thumbable = nil
    params.each do |name, value|
      if name =~ /(.+)_id$/
        @thumbable = $1.classify.constantize.find(value)
      end
    end
    @itemable = @thumbable.itemable if @thumbable.respond_to?(:itemable)
  end

  def thumb_params
    params.require(:thumb).permit(:name, :file, :description, :is_default, :is_kit_image)
  end
end

app/controllers/back_end_controller.rb
class BackEndController < ApplicationController
  before_action :authenticate_user!

  layout 'back_end'

  private

  def set_locale
    I18n.locale = :en
  end
end

app/views/back_end/bed_prices/_edit_price_cell.html.erb
<td>
  <%= f.fields_for :bed_prices, f.object.price_for_editing(dimension, has_decoration, has_rack) do |ff| %>
    <%= ff.hidden_field :id %>
    <%= ff.hidden_field :dimension_id %>
    <%= ff.hidden_field :has_decoration %>
    <%= ff.hidden_field :has_rack %>
    <%= ff.text_field :price %>
  <% end %>
</td>

app/views/back_end/bed_prices/_edit_prices_row.html.erb
<tr>
  <td>
    Decoration: (<%= has_decoration %>), Rack: (<%= has_rack %>)
  </td>
  <% f.object.dimensions.order(sequence: :asc).each do |dimension| %>
    <%= render "#{mode}_price_cell", f: f, dimension: dimension, has_decoration: has_decoration, has_rack: has_rack %>
  <% end %>
</tr>

app/views/back_end/bed_prices/_show_price_cell.html.erb
<td>
  <% bed_price = f.object.price_for_editing(dimension, has_decoration, has_rack) %>
  <%= bed_price.price %>
</td>

app/views/back_end/bed_prices/edit.html.erb
<h1>Editing bed '<%= @bed.name %>' prices</h1>

<%= form_for @bed, url: back_end_bed_prices_path(@bed) do |f| %>
  <% if @bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% @bed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-stripped table-bordered table-hover">
    <tr>
      <th></th>
      <% @bed.dimensions.order(sequence: :asc).each do |dimension| %>
        <th>
          <%= dimension.name %>
        </th>
      <% end %>
    </tr>
    <%= render 'edit_prices_row', f: f, mode: 'edit', has_decoration: false, has_rack: false %>
    <%= render 'edit_prices_row', f: f, mode: 'edit', has_decoration: true,  has_rack: false %>
    <%= render 'edit_prices_row', f: f, mode: 'edit', has_decoration: false, has_rack: true  %>
    <%= render 'edit_prices_row', f: f, mode: 'edit', has_decoration: true,  has_rack: true  %>
  </table>

  <div class="actions">
    <%= f.submit value: 'Save changes', class: "btn btn-success" %>
    <% if @bed.persisted? %>
      <%= link_to 'Show', back_end_bed_prices_path(@bed), class: 'btn btn-default' %>
    <% end %>
    <%= link_to 'Back to bed', back_end_bed_path(@bed), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/back_end/bed_prices/show.html.erb
<h1>Bed '<%= @bed.name %>' prices</h1>

<%= form_for @bed, url: back_end_bed_prices_path(@bed) do |f| %>
  <table class="table table-stripped table-bordered table-hover">
    <tr>
      <th></th>
      <% @bed.dimensions.order(sequence: :asc).each do |dimension| %>
        <th>
          <%= dimension.name %>
        </th>
      <% end %>
    </tr>
    <%= render 'edit_prices_row', f: f, mode: 'show', has_decoration: false, has_rack: false %>
    <%= render 'edit_prices_row', f: f, mode: 'show', has_decoration: true,  has_rack: false %>
    <%= render 'edit_prices_row', f: f, mode: 'show', has_decoration: false, has_rack: true  %>
    <%= render 'edit_prices_row', f: f, mode: 'show', has_decoration: true,  has_rack: true  %>
  </table>
<% end %>

<%= link_to 'Edit prices', edit_back_end_bed_prices_path(@bed), class: 'btn btn-primary' %>
<%= link_to 'Back to bed', back_end_bed_path(@bed), class: 'btn btn-default' %>