config/routes.rb
Rails.application.routes.draw do
  concern :thumbs do
    resources :thumbs
  end

  root to: 'high_voltage/pages#show', id: 'home'

  devise_for :users
  resources :beds, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :linens, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :purchases, only: [:edit, :update, :show]

  namespace :back_end do
    resources :beds, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :colors, concerns: [:thumbs]
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'bed_prices', only: [:show, :edit, :update]
      resource  :kit_prices, controller: 'kit_prices', only: [:show, :edit, :update]
    end
    resources :purchases, only: [:index]

    resources :linens, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'linen_prices', only: [:show, :edit, :update]
    end
    resources :linen_purchases, only: [:index]
  end
end

app/models/linen.rb
class Linen < ActiveRecord::Base
  has_many :dimensions, as: :itemable, dependent: :destroy
  has_many :kits, as: :itemable, dependent: :destroy
  has_many :linen_prices
  has_many :purchases, as: :itemable
  has_many :thumbs, as: :thumbable, dependent: :destroy

  accepts_nested_attributes_for :linen_prices, reject_if: proc { |attributes| attributes['price'].to_f == 0 }, allow_destroy: true

  def main_thumb
    thumbs.where(is_kit_image: false).order(is_default: :desc, sequence: :asc).first
  end

  def price_for_editing(dimension, has_decoration, kit)
    linen_prices.find_or_initialize_by(
        dimension:      dimension,
        has_decoration: has_decoration,
        kit:            kit
      )
  end

  def decoration_prices
    query = <<-SQL.squish
      SELECT w.linen_id, w.dimension_id, w.price - wo.price AS price
        FROM linen_prices w
        JOIN linen_prices wo ON w.linen_id     = wo.linen_id
                            AND w.dimension_id = wo.dimension_id
                            AND w.kit_id       = wo.kit_id
       WHERE w.linen_id = #{id}
         AND w.has_decoration = true
         AND wo.has_decoration = false
    SQL

    LinenPrice.find_by_sql(query)
  end
end

# == Schema Information
#
# Table name: linens
#
#  id             :integer          not null, primary key
#  code           :string(255)
#  name           :string(255)
#  sequence       :integer
#  description_lv :text
#  description_ru :text
#  description_en :text
#  created_at     :datetime
#  updated_at     :datetime
#  has_decoration :boolean          default(FALSE)
#

app/controllers/back_end/linens_controller.rb
class BackEnd::LinensController < BackEndController
  before_action :set_linen, only: [:show, :edit, :update, :destroy]

  # GET /back_end/linens
  def index
    @linens = Linen.all.order(sequence: :asc)
  end

  # GET /back_end/linens/1
  def show
  end

  # GET /back_end/linens/new
  def new
    @linen = Linen.new
  end

  # GET /back_end/linens/1/edit
  def edit
  end

  # POST /back_end/linens
  def create
    @linen = Linen.new(linen_params)

    if @linen.save
      redirect_to back_end_linen_path(@linen), notice: "Veiksmīgi tika izveidots komplekts '#{@linen.name}'"
    else
      render :new
    end
  end

  # PATCH/PUT /back_end/linens/1
  def update
    if @linen.update(linen_params)
      redirect_to back_end_linen_path(@linen), notice: "Veiksmīgi tika labots komplekts '#{@linen.name}'"
    else
      render :edit
    end
  end

  # DELETE /back_end/linens/1
  def destroy
    @linen.destroy
    redirect_to back_end_linens_url, notice: 'LInen was successfully destroyed.'
  end

  private

  def set_linen
    @linen = Linen.find(params[:id])
  end

  def linen_params
    params.require(:linen).permit(
      :code, :name, :sequence, :has_decoration, :description_lv, :description_ru, :description_en
    )
  end
end

app/controllers/linens_controller.rb
class LinensController < ApplicationController
  # GET /linens
  def index
    @linens = Linen.all.order('sequence ASC')
  end

  def show
    @linen = Linen.where(code: params[:id]).first
    @purchase = @linen.purchases.build
    render :show
  end

  def set_active_nav_tab
    @active_nav_tab = :linens
  end
end

app/views/linens/index.html.erb
<div class="main" id="shop-grid">
  <div class="innerBox">
    <div class="gridContainer">
      <% @linens.each do |linen| %>
        <div class="grid-item">
          <div class="grid-itemTitle"><%= linen.name %></div>
          <% link_content = linen.main_thumb ? image_tag(linen.main_thumb.file.w280.url) : linen.name %>
          <%= link_to link_content, friendly_linen_path(linen) %>
        </div>
      <% end %>
    </div><!-- end.gridContainer -->

  </div><!-- end.innerBox -->
</div><!-- end.main -->

app/views/linens/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "linens" %>
<% end %>

<% linen_prices_json      = linen_prices_for_data(@linen) %>
<% decoration_prices_json = linen_decoration_prices_for_data(@linen) %>
<%= form_for @purchase, url: linen_purchases_path(@linen), data: {linen_prices: linen_prices_json, decoration_prices: decoration_prices_json}, html: {id: 'linen-purchase-form'} do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" id="lp-price-id" class="lp-price-id" name="price_id" />
  <input type="hidden" id="lp-kit-price-id" class="lp-kit-price-id" name="purchase[kit_price_id]" />

  <div class="main" id="shop-item">

    <div class="leftCol">
      <div class="innerBox">
        <h1 class="dynamic"><%= @linen.name %></h1>
        <p><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>

        <div class="shop_size_selector" style="background-color: #fafafa;">
          <h3>
            <%= t '.linen_size' %> (<span class="dynamic" id="selected-dimension-name"></span>)
          </h3>

          <table width="320" border="0">
            <tr>
              <% @linen.dimensions.order(sequence: :asc).each do |dim| %>
                <td>
                  <input type="radio" id="dim-<%= dim.id %>" class="lp-dimension lp-changer css-checkbox" name="dimension" value="<%= dim.id %>" <%= 'checked="checked"' if dim.is_default? %> data-name="<%= dim.name %>" />
                  <label for="dim-<%= dim.id %>" class="css-label radGroup2"><%= dim.short_name %></label>
                </td>
              <% end %>
            </tr>
          </table>
        </div>

        <p><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>

        <div class="linenSelect">
          <% default_kit = @linen.kits.order(is_default: :desc, sequence: :asc).first %>
          <input type="hidden" id="lp-kit" class="lp-kit lp-changer" name="kit" value="<%= default_kit.try(:id) %>" />

          <% if @linen.kits.count > 0 %>
            <table class="linenSelect">
              <% @linen.kits.order(sequence: :asc).each do |kit| %>
                <tr>
                <td>
                  <input type="radio" name="radiog_dark2" id="kit<%= kit.id %>" class="css-checkbox lp-kit-changer" data-kit-id="<%= kit.id %>" data-kit-description="<%= lf(kit, :description) %>" <%= kit == default_kit ? 'checked' : '' %> />
                  <label for="kit<%= kit.id %>" class="css-label radGroup3"><%= lf(kit, :name) %></label>
                </td>
                </tr>
              <% end %>
            </table>
          <% end %>

          <% if @linen.has_decoration? %>
            <table class="linenSelect">
              <tr>
                <td class="checkbox-cell">
                  <input type="checkbox" class="lp-has-decoration lp-changer" name="has_decoration" value="" id="lp-has-decoration" />
                  <label for="lp-has-decoration" class="checkbox-label"><%= t('.include_decorative_cover') %></label>
                </td>
              </tr>
            </table> <!---->
          <% end %>
        </div><!-- end linenSelect -->

        <% if false %>
          <!-- Always hide this block - Girls requested this -->
          <p><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>

          <div class="cena">
            <table width="303" border="0">
              <tr>
                <td class="txt"><%= t '.linen_price' %>:</td>
                <td class="sum">
                  € <span id='linen-price'></span>
                </td>
              </tr>
              <% if @linen.has_decoration? %>
                <tr class="linen">
                  <td class="txt"><%= t '.decoration_price' %>:</td>
                  <td class="sum">
                    € <span id='decoration-price'></span>
                  </td>
                </tr>
              <% end %>
              <tr class="totalCost">
                <td class="txt" width="52"><%= t '.total_price' %>:</td>
                <td class="sum" width="273">€ <span id='actual-price-price'></span></td>
                </tr>
              </table>
          </div>
        <% end %>

        <%= f.submit value: t('create_purchase'), class: "btn-style" %>

        <div class="subNav">
          <ul>
            <li>
              <%= link_to t('.more_info'), page_path(id: 'about', anchor: "shopping_guidelines") %>
            </li>
          </ul>
        </div>
      </div><!-- end.innerBox -->
    </div><!-- end.leftCol -->

    <div class="rightCol">
      <div class="innerBox">
        <div class="breadcrumbs"><%= link_to t('.all_linens'), linens_path %> / <%= @linen.name %></div>

        <div id="bed-images-container" class="gallery" style="padding: 10px 0 0 0">
          <div class="gallery_img">
            <% if @linen.thumbs.any? %>
              <%= link_to image_tag(@linen.main_thumb.file.w510.url), @linen.main_thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
            <% end %>
          </div>
          <div class="gallery_th">
            <% if @linen.thumbs.any? %>

              <% images = @linen.thumbs.to_a - [@linen.main_thumb] %>
              <% images.each do |thumb| %>
                <%= link_to image_tag(thumb.file.w60.url), thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="blueimp-gallery" class="blueimp-gallery">
          <div class="slides"></div>
          <h3 class="title"></h3>
          <a class="prev">‹</a>
          <a class="next">›</a>
          <a class="play-pause"></a>
          <ol class="indicator"></ol>
        </div>

        <!-- end gallery-->


        <div class="descr">
          <%= rich_text lf(@linen, :description) %>
        </div>
      </div> <!-- end.innerBox -->
    </div><!-- end.rightCol -->
    <span class="clear"></span>
  </div><!-- end.main -->
<% end %>