config/routes.rb
Rails.application.routes.draw do
  concern :thumbs do
    resources :thumbs
  end

  root to: 'high_voltage/pages#show', id: 'home'

  devise_for :users
  resources :beds, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :linens, only: [:index, :show] do
    resources :purchases, only: [:create]
  end

  resources :purchases, only: [:edit, :update, :show]

  namespace :back_end do
    resources :beds, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :colors, concerns: [:thumbs]
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'bed_prices', only: [:show, :edit, :update]
      resource  :kit_prices, controller: 'kit_prices', only: [:show, :edit, :update]
    end
    resources :purchases, only: [:index]

    resources :linens, only: [:index, :new, :create, :edit, :update, :show], concerns: [:thumbs] do
      resources :dimensions
      resources :kits, concerns: [:thumbs]
      resource  :prices, controller: 'linen_prices', only: [:show, :edit, :update]
    end
    resources :linen_purchases, only: [:index]
  end
end

app/models/bed.rb
class Bed < ActiveRecord::Base
  has_many :colors, as: :itemable, dependent: :destroy
  has_many :dimensions, as: :itemable, dependent: :destroy
  has_many :kits, as: :itemable, dependent: :destroy
  has_many :bed_prices, dependent: :destroy
  has_many :kit_prices, dependent: :destroy
  has_many :purchases, as: :itemable
  has_many :thumbs, as: :thumbable, dependent: :destroy

  validates :code, uniqueness: true
  validates :name, :code, presence: true

  after_create :create_default_kit

  accepts_nested_attributes_for :bed_prices, reject_if: proc { |attributes| attributes['price'].to_f == 0 }, allow_destroy: true
  accepts_nested_attributes_for :kit_prices, allow_destroy: true

  def main_thumb
    thumbs.where(is_kit_image: false).order(is_default: :desc, sequence: :asc).first
  end

  def kit_image
    thumbs.where(is_kit_image: true).first
  end

  def price_for_editing(dimension, has_decoration, has_rack)
    bed_prices.find_or_initialize_by(
        dimension: dimension,
        has_decoration: has_decoration,
        has_rack: has_rack
      )
  end

  def kit_price_for_editing(kit, dimension)
    kit_prices.find_or_initialize_by(
        dimension: dimension,
        kit: kit
      )
  end

  def decoration_prices
    query = <<-SQL.squish
      SELECT w.bed_id, w.dimension_id, w.has_rack, w.price - wo.price AS price
        FROM bed_prices w
        JOIN bed_prices wo ON w.bed_id = wo.bed_id
                          AND w.has_rack = wo.has_rack
                          AND w.dimension_id = wo.dimension_id
       WHERE w.bed_id = #{id}
         AND w.has_decoration = true
         AND wo.has_decoration = false
    SQL

    BedPrice.find_by_sql(query)
  end

  private

  def create_default_kit
    kits.create(
      name_lv: 'Nav komplekta',
      name_en: 'No linen',
      name_ru: 'Netu komplekta',
      is_default: true
    )
  end

end

# == Schema Information
#
# Table name: beds
#
#  id             :integer          not null, primary key
#  code           :string(255)
#  name           :string(255)
#  sequence       :integer
#  has_decoration :boolean
#  has_rack       :boolean
#  description_lv :text
#  description_ru :text
#  description_en :text
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/back_end/beds_controller.rb
class BackEnd::BedsController < BackEndController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  # GET /beds
  def index
    @beds = Bed.all.order(sequence: :asc)
  end

  # GET /beds/1
  def show
  end

  # GET /beds/new
  def new
    @bed = Bed.new
  end

  # GET /beds/1/edit
  def edit
  end

  # POST /beds
  def create
    @bed = Bed.new(bed_params)

    if @bed.save
      redirect_to back_end_bed_path(@bed), notice: "Veiksmīgi tika izveidota gulta '#{@bed.name}'"
    else
      render :new
    end
  end

  # PATCH/PUT /beds/1
  def update
    if @bed.update(bed_params)
      redirect_to back_end_bed_path(@bed), notice: "Veiksmīgi tika labota gulta '#{@bed.name}'"
    else
      render :edit
    end
  end

  # DELETE /beds/1
  def destroy
    @bed.destroy
    redirect_to back_end_beds_url, notice: 'Bed was successfully destroyed.'
  end

  private

  def set_bed
    @bed = Bed.find(params[:id])
  end

  def bed_params
    params.require(:bed).permit(
      :code, :name, :sequence, :has_decoration, :has_rack, :description_lv, :description_ru, :description_en
    )
  end
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  # GET /beds
  def index
    @beds = Bed.all.order('sequence ASC')
  end

  def show
    @bed = Bed.where(code: params[:id]).first
    @purchase = @bed.purchases.build
    render :show
  end

  def set_active_nav_tab
    @active_nav_tab = :beds
  end
end

app/helpers/beds_helper.rb
module BedsHelper
  def bed_prices_for_data(bed)
    bed.bed_prices.map do |bed_price|
      {
        id:             bed_price.id,
        has_decoration: bed_price.has_decoration,
        has_rack:       bed_price.has_rack,
        dimension_id:   bed_price.dimension_id,
        price:          bed_price.price
      }
    end
  end

  def bed_decoration_prices_for_data(bed)
    bed.decoration_prices.map do |bed_price|
      {
        has_rack:       bed_price.has_rack,
        dimension_id:   bed_price.dimension_id,
        price:          bed_price.price
      }
    end
  end

  def linen_decoration_prices_for_data(linen)
    linen.decoration_prices.map do |linen_price|
      {
        dimension_id:   linen_price.dimension_id,
        price:          linen_price.price
      }
    end
  end

  def bed_kit_prices_for_data(bed)
    bed.kit_prices.map do |kit_price|
      {
        id:             kit_price.id,
        kit_id:         kit_price.kit_id,
        dimension_id:   kit_price.dimension_id,
        price:          kit_price.price
      }
    end
  end

  def linen_prices_for_data(linen)
    linen.linen_prices.map do |linen_price|
      {
        id:             linen_price.id,
        has_decoration: linen_price.has_decoration,
        kit_id:         linen_price.kit_id,
        dimension_id:   linen_price.dimension_id,
        price:          linen_price.price
      }
    end
  end
end

app/views/beds/index.html.erb
<div class="main" id="shop-grid">
  <div class="innerBox">
    <div class="gridContainer">
      <% @beds.each do |bed| %>
        <div class="grid-item">
          <div class="grid-itemTitle"><%= bed.name %></div>
          <% link_content = bed.main_thumb ? image_tag(bed.main_thumb.file.w280.url) : bed.name %>
          <%= link_to link_content, friendly_bed_path(bed) %>
        </div>
      <% end %>
    </div><!-- end.gridContainer -->

  </div><!-- end.innerBox -->
</div><!-- end.main -->

app/views/beds/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "beds" %>
<% end %>

<% bed_prices_json        = bed_prices_for_data(@bed) %>
<% kit_prices_json        = bed_kit_prices_for_data(@bed) %>
<% decoration_prices_json = bed_decoration_prices_for_data(@bed) %>
<%= form_for @purchase, url: bed_purchases_path(@bed), data: {bed_prices: bed_prices_json, kit_prices: kit_prices_json, decoration_prices: decoration_prices_json}, html: {id: 'bed-purchase-form'} do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" id="bp-price-id" class="bp-price-id" name="price_id" />
  <input type="hidden" id="bp-kit-price-id" class="bp-kit-price-id" name="purchase[kit_price_id]" />

  <div class="main" id="shop-item">
    <div class="leftCol">
      <div class="innerBox">
        <h1 class="dynamic"><%= @bed.name %></h1>
        <p style="margin-top:-10px; padding-bottom:13px;"><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>
        <div class="shop_thumbs_img">
          <input type="hidden" id="bp-color" class="bp-color" name="purchase[color_id]" value="" />
          <% if @bed.colors.exists? %>
            <% @bed.colors.order(sequence: :asc).each_slice(5) do |colors| %>
              <div>
                <% colors.each do |color| %>
                  <a href="<%= color.thumbs.first.file.w200.url %>" data-color-id="<%= color.id %>" data-color-name="<%= lf(color, :name) %>" class="bp-color-changer <%= 'bp-color-selected' if color.id == @purchase.color_id %>"><%- if color.thumbs.first -%><%= image_tag color.thumbs.first.file.w46.url, alt: lf(color, :name) %><%- end -%></a>
                <% end %>
              </div>
            <% end %>
          <% end %>

          <p>
            <span class="dynamic">
              <%= t '.color_scheme' %>:
            </span>
            <span class="dynamic" id="selected-color-name"></span>
          </p>
        </div>
        <!--end.shop_thumbs_img -->

        <p>
          <img src="/images/css/line_dotted.gif" width="497" height="1" />
        </p>

        <div class="shop_size_selector" style="background-color: #fafafa;">
          <h3>
            <%= t '.bed_size' %> (<span class="dynamic" id="selected-dimension-name"></span>)
          </h3>

          <table width="320" border="0">
            <tr>
              <% @bed.dimensions.order(sequence: :asc).each do |dim| %>
                <td>
                  <input type="radio" id="dim-<%= dim.id %>" class="bp-dimension bp-changer css-checkbox" id="checkboxG4" name="dimension" value="<%= dim.id %>" <%= 'checked="checked"' if dim.is_default? %> data-name="<%= dim.name %>" />
                  <label for="dim-<%= dim.id %>" class="css-label radGroup2"><%= dim.short_name %></label>
                </td>
              <% end %>
            </tr>
            <tr>
              <td colspan="3" class="checkbox-cell">
                <input type="checkbox" class="bp-has-rack bp-changer" name="has_rack" value="" id="bp-has-rack" />
                <label for="bp-has-rack" class="checkbox-label"><%= t '.has_rack' %></label>
              </td>
            </tr>
          </table>
        </div>

        <p><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>

        <div class="linenSelect">
          <% default_kit = @bed.kits.order(is_default: :desc, sequence: :asc).first %>
          <input type="hidden" id="bp-kit" class="bp-kit bp-changer" name="kit" value="<%= default_kit.try(:id) %>" />

          <% if @bed.kit_image %>
            <%= image_tag(@bed.kit_image.file.w150.url, class: "decoLinenImg") %>
          <% end %>

          <% if @bed.has_decoration? %>
            <table class="linenSelect">
              <tr>
                <td colspan="3" class="checkbox-cell">
                  <input type="checkbox" class="bp-has-decoration bp-changer" name="has_decoration" value="" id="bp-has-decoration" />
                  <label for="bp-has-decoration" class="checkbox-label"><%= t('.include_decorative_cover') %></label>
                </td>
              </tr>
              <tr>
                <td class="and"><img src="/images/and_imgL.gif"  height="7" /><%= t('.and') %><img src="/images/and_imgR.gif" width="43" height="7" /></td>
              </tr>
            </table> <!---->
          <% end %>

          <% if @bed.kits.count > 1 %>
            <table class="linenSelect">
              <% @bed.kits.order(sequence: :asc).each do |kit| %>
                <tr>
                <td>
                  <input type="radio" name="radiog_dark2" id="kit<%= kit.id %>" class="css-checkbox bp-kit-changer" data-kit-id="<%= kit.id %>" data-kit-description="<%= lf(kit, :description) %>" <%= kit == default_kit ? 'checked' : '' %> />
                  <label for="kit<%= kit.id %>" class="css-label radGroup3"><%= lf(kit, :name) %></label>
                </td>
                </tr>
              <% end %>
              </table>
          <% end %>
        </div><!-- end linenSelect -->

        <p><img src="/images/css/line_dotted.gif" width="497" height="1" /></p>

        <% if false %>
          <!-- Always hide this block - Girls requested this -->
          <div class="cena">
            <table width="303" border="0">
              <tr class="bed">
                <td class="txt" width="220"><%= t '.bed_price' %>:</td>
                <td class="sum" width="auto">
                  € <span id='bed-price'></span>
                </td>
              </tr>
              <% if @bed.has_decoration? %>
                <tr class="bed">
                  <td class="txt"><%= t '.decoration_price' %>:</td>
                  <td class="sum">
                    € <span id='decoration-price'></span>
                  </td>
                </tr>
              <% end %>
              <tr class="linen">
                <td class="txt"><%= t '.kit_price' %>:</td>
                <td class="sum">
                  € <span id='kit-price'></span>
                </td>
              </tr>
              <tr class="totalCost">
                <td class="txt"><%= t '.total_price' %>:</td>
                <td class="sum">
                  € <span id='actual-price-price'></span>
                </td>
              </tr>
              <tr class="price-hint">
                <td colspan="3"><%= t '.not_included' %></td>
              </tr>
            </table>
          </div>
        <% end %>

        <%= f.submit value: t('create_purchase'), class: "btn-style" %>
        <div class="subNav">
          <ul>
            <li>
              <%= link_to t('.more_info'), page_path(id: 'about', anchor: "shopping_guidelines") %>
            </li>
          </ul>
        </div>
      </div>
      <!-- end.innerBox -->
    </div>
    <!-- end.leftCol -->


    <div class="rightCol">
      <div class="innerBox">
        <div class="breadcrumbs"><%= link_to t('.all_beds'), beds_path %> / <%= @bed.name %></div>
        <div id="bed-images-container" class="gallery" style="padding: 10px 0 0 0">
          <div class="gallery_img">
            <% if @bed.thumbs.any? %>
              <%= link_to image_tag(@bed.main_thumb.file.w510.url), @bed.main_thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
              <!-- <%= image_tag(@bed.main_thumb.file.w510.url) %> -->
            <% end %>
          </div>
          <div class="gallery_th">
            <% if @bed.thumbs.any? %>

              <% images = @bed.thumbs.where(is_kit_image: false).to_a - [@bed.main_thumb] %>
              <% images.each do |thumb| %>
                <%= link_to image_tag(thumb.file.w60.url), thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
                <!-- <%= image_tag(thumb.file.w60.url) %> -->
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="blueimp-gallery" class="blueimp-gallery">
          <div class="slides"></div>
          <h3 class="title"></h3>
          <a class="prev">‹</a>
          <a class="next">›</a>
          <a class="play-pause"></a>
          <ol class="indicator"></ol>
        </div>

        <!-- end gallery-->


        <div class="descr">
          <%= rich_text lf(@bed, :description) %>
        </div>
      </div>
      <!-- end.innerBox -->
    </div>
    <!-- end.rightCol -->
    <span class="clear"></span>
  </div>
  <!-- end.main -->
<% end %>

app/views/beds/show_incomplete.html.erb
<% bed_prices_json = bed_prices_for_data(@bed) %>
<% kit_prices_json = bed_kit_prices_for_data(@bed) %>
<%= form_for @purchase, url: bed_purchases_path(@bed), data: {bed_prices: bed_prices_json, kit_prices: kit_prices_json}, html: {id: 'purchase-form'} do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" id="bp-price-id" class="bp-price-id" name="bed_purchase[bed_price_id]" />
  <input type="hidden" id="bp-kit-price-id" class="bp-kit-price-id" name="bed_purchase[kit_price_id]" />

  <!-- label for="bp-has-decoration">Ir dekorācija</label-->
  <input type="hidden" class="bp-has-decoration bp-changer" name="has_decoration" value="" id="bp-has-decoration" />

  <div class="main" id="shop-item">
    <div class="leftCol">
      <div class="innerBox">
        <h1 class="dynamic"><%= @bed.name %></h1>
        <p style="font-size:13px; color:#999; border:1px solid #f1f1f1; background:#fcfcfc; text-align:center; padding:50px;">
          The online shop is going to be lounched on october 27th, 2014.
        </p>
      </div>
      <!-- end.innerBox -->
    </div>
    <!-- end.leftCol -->


    <div class="rightCol">
      <div class="innerBox">
        <div class="breadcrumbs"><%= link_to t('.all_beds'), beds_path %> / <%= @bed.name %></div>
        <div id="bed-images-container" class="gallery" style="padding: 10px 0 0 0">
          <div class="gallery_img">
            <% if @bed.thumbs.any? %>
              <%= link_to image_tag(@bed.main_thumb.file.w510.url), @bed.main_thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
              <!-- <%= image_tag(@bed.main_thumb.file.w510.url) %> -->
            <% end %>
          </div>
          <div class="gallery_th">
            <% if @bed.thumbs.any? %>

              <% images = @bed.thumbs.to_a - [@bed.main_thumb] %>
              <% images.each do |thumb| %>
                <%= link_to image_tag(thumb.file.w60.url), thumb.file.w800.url, target: '_blank', data: {gallery: '#blueimp-gallery'} %>
                <!-- <%= image_tag(thumb.file.w60.url) %> -->
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="blueimp-gallery" class="blueimp-gallery">
          <div class="slides"></div>
          <h3 class="title"></h3>
          <a class="prev">‹</a>
          <a class="next">›</a>
          <a class="play-pause"></a>
          <ol class="indicator"></ol>
        </div>

        <!-- end gallery-->


        <%= rich_text lf(@bed, :description) %>
      </div>
      <!-- end.innerBox -->
    </div>
    <!-- end.rightCol -->
    <span class="clear"></span>
  </div>
  <!-- end.main -->
<% end %>